# Project: ±M®×3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o prime.o
LINKOBJ  = main.o prime.o
LIBS     = -L"D:/USER/Downloads/DevCppPortable/MinGW64/lib" -L"D:/USER/Downloads/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/USER/Downloads/DevCppPortable/MinGW64/include" -I"D:/USER/Downloads/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/USER/Downloads/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/USER/Downloads/DevCppPortable/MinGW64/include" -I"D:/USER/Downloads/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"D:/USER/Downloads/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/USER/Downloads/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = prime.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

prime.o: prime.c
	$(CC) -c prime.c -o prime.o $(CFLAGS)
